export class Enemy{
 constructor(x,y,type){this.x=x;this.y=y;this.type=type;this.w=type==="bat"?40:44;this.h=type==="bat"?30:50;this.hp={crawler:38,bat:28,guardian:85,knight:70,mage:45}[type]||40;this.max=this.hp;this.vx=0;this.vy=0;this.cool=0;this.dead=false;this.dir=-1}
 update(dt,g){if(this.dead)return;const dx=g.player.x-this.x,dy=g.player.y-this.y;if(Math.abs(dx)<620){this.dir=Math.sign(dx)||this.dir;this.vx=this.dir*(this.type==="guardian"?24:this.type==="bat"?60:42);if(this.type==="bat")this.y+=Math.sin(performance.now()/280+this.x)*25*dt;else{this.vy+=1500*dt;const old=this.y,ny=this.y+this.vy*dt;let ground=600-this.h;for(const p of g.world.platforms)if(this.x+this.w>p.x&&this.x<p.x+p.w&&old+this.h<=p.y+8&&ny+this.h>=p.y&&this.vy>=0)ground=Math.min(ground,p.y-this.h);this.y=Math.min(ny,ground);if(this.y===ground)this.vy=0}}this.x+=this.vx*dt;this.cool-=dt;if(Math.abs(dx)<55&&Math.abs(dy)<65&&this.cool<=0){g.player.hitBy(this.type==="guardian"?13:8,g);this.cool=this.type==="knight"?.9:1.2}if(this.type==="mage"&&Math.abs(dx)<500&&this.cool<=0){g.projectiles.push({x:this.x,y:this.y+20,vx:dx<0?-190:190,life:3,damage:11,boss:true});this.cool=2}}
 hit(d,g){if(this.dead)return;this.hp-=d;g.particles.burst(this.x,this.y,8,"#d4bc72");if(this.hp<=0){this.dead=true;g.player.coins+=4;g.player.gainXP(25,g);g.audio.enemyDeath()}}
 draw(c,cam){const x=this.x-cam.x,y=this.y-cam.y;c.save();c.translate(x,y);if(this.dir<0)c.scale(-1,1);if(this.type==="bat"){c.fillStyle="#594c83";c.beginPath();c.moveTo(0,15);c.lineTo(16,0);c.lineTo(40,15);c.lineTo(25,18);c.lineTo(40,30);c.lineTo(18,24);c.lineTo(0,30);c.lineTo(13,17);c.closePath();c.fill()}else{const colors={crawler:"#4e654c",guardian:"#626b75",knight:"#684d55",mage:"#6e5c86"};c.fillStyle=colors[this.type]||"#555";c.fillRect(2,9,this.w-4,this.h-9);c.fillStyle="#d8bd68";c.fillRect(10,17,5,5);c.fillRect(29,17,5,5);if(this.type==="knight"){c.strokeStyle="#bcae83";c.lineWidth=4;c.beginPath();c.moveTo(34,30);c.lineTo(55,12);c.stroke()}if(this.type==="mage"){c.fillStyle="#34264b";c.beginPath();c.arc(22,8,17,0,7);c.fill()}}c.restore()}}
export class Boss{
 constructor(x,y){this.x=x;this.y=y;this.w=96;this.h=86;this.hp=850;this.max=this.hp;this.phase=1;this.cool=1;this.dead=false;this.dir=-1}
 update(dt,g){if(this.dead)return;this.phase=this.hp<this.max*.6?2:this.hp<this.max*.28?3:1;this.cool-=dt;this.dir=Math.sign(g.player.x-this.x)||this.dir;this.x+=Math.sin(performance.now()/800)*20*dt;if(this.cool<=0){if(this.phase===1){g.projectiles.push({x:this.x,y:this.y+30,vx:this.dir*270,life:3,damage:15,boss:true});this.cool=1.2}else if(this.phase===2){for(let i=-1;i<=1;i++)g.projectiles.push({x:this.x,y:this.y+25,vx:this.dir*(230+i*70),life:3,damage:17,boss:true});this.cool=.9}else{for(let i=0;i<6;i++)g.projectiles.push({x:this.x,y:this.y+25,vx:Math.cos(i)*280,life:2.4,damage:20,boss:true});this.cool=1.15}if(Math.abs(g.player.x-this.x)<130)g.player.hitBy(18,g);g.shake=.08}}
 hit(d,g){this.hp-=d;g.particles.burst(this.x,this.y,12,"#a94767");g.shake=.05;if(this.hp<=0){this.dead=true;g.particles.burst(this.x,this.y,80,"#d9bd69");g.audio.bossDeath()}}
 draw(c,cam){const x=this.x-cam.x,y=this.y-cam.y;c.save();c.translate(x,y);c.fillStyle=this.phase===3?"#6e234c":"#481d3b";c.fillRect(5,10,86,76);c.fillStyle="#d8c178";c.fillRect(23,28,8,8);c.fillRect(65,28,8,8);c.strokeStyle="#9b7c52";c.lineWidth=7;c.beginPath();c.moveTo(16,12);c.lineTo(2,-12);c.moveTo(80,12);c.lineTo(96,-12);c.stroke();c.restore()}}
