import {Player} from "./player.js"; import {World} from "./world.js"; import {Enemy,Boss} from "./enemies.js"; import {ParticleSystem} from "./particles.js"; import {AudioFX} from "./audio.js"; import {Camera} from "./camera.js"; import {UI} from "./ui.js"; import {SaveSystem} from "./save.js";
export class Game{
 constructor(canvas){this.c=canvas;this.x=canvas.getContext("2d");this.W=1280;this.H=720;this.state="menu";this.last=0;this.keys={};this.ui={};this.world=new World();this.particles=new ParticleSystem();this.audio=new AudioFX();this.camera=new Camera(this.W,this.H);this.saveSys=new SaveSystem("shadowbound-v2");this.uiSys=new UI(this);this.enemies=[];this.projectiles=[];this.coins=[];this.chests=[];this.npcs=[];this.checkpoints=[];this.boss=null;this.dialog=null;this.shake=0;this.areaIndex=0}
 start(load){this.state="playing";this.world.build();this.player=new Player(150,430);this.spawnContent();if(load)this.restore();this.uiSys.refresh();this.audio.init()}
 spawnContent(){this.enemies=[];for(const [x,y,t] of [[650,520,"crawler"],[1050,440,"crawler"],[1450,500,"bat"],[1900,450,"guardian"],[2450,520,"crawler"],[3050,380,"bat"],[3500,470,"knight"],[4200,410,"mage"],[4850,520,"crawler"],[5550,440,"guardian"],[6250,370,"bat"],[7000,510,"knight"],[7650,430,"mage"]])this.enemies.push(new Enemy(x,y,t));
 this.coins=[900,1320,1780,2200,2800,3350,4000,4550,5200,5850,6500,7200,7900].map(x=>({x,y:this.world.groundY(x)-28,taken:false}));
 this.chests=[{x:1200,y:this.world.groundY(1200)-38,open:false,reward:"Moonsteel Sword"},{x:3900,y:this.world.groundY(3900)-38,open:false,reward:"Mana Upgrade"},{x:6100,y:this.world.groundY(6100)-38,open:false,reward:"Shadow Spell"}];
 this.npcs=[{x:340,y:470,name:"Elder Rowan",text:"The old kingdom fell when something beneath the castle awakened. Follow the shrine lights."},{x:2200,y:400,name:"Mira",text:"The mines hide a crystal that remembers every oath sworn by the forgotten kings."},{x:5300,y:410,name:"Warden",text:"The final fortress is ahead. Do not mistake silence for safety."}];
 this.checkpoints=[{x:1550,y:this.world.groundY(1550)-58,active:false},{x:3600,y:this.world.groundY(3600)-58,active:false},{x:5700,y:this.world.groundY(5700)-58,active:false},{x:7600,y:this.world.groundY(7600)-58,active:false}]}
 loop(t){const dt=Math.min(.033,(t-this.last)/1000||0);this.last=t;if(this.state==="playing")this.update(dt);this.draw();requestAnimationFrame(v=>this.loop(v))}
 update(dt){this.player.update(dt,this);for(const e of this.enemies)e.update(dt,this);this.enemies=this.enemies.filter(e=>!e.dead);for(const p of this.projectiles){p.x+=p.vx*dt;p.life-=dt;if(p.boss)this.player.hitBy(p.damage,this);else{for(const e of this.enemies)if(Math.abs(p.x-e.x)<38&&Math.abs(p.y-e.y)<60){e.hit(p.damage,this);p.life=0}if(this.boss&&Math.abs(p.x-this.boss.x)<60&&Math.abs(p.y-this.boss.y)<80){this.boss.hit(p.damage,this);p.life=0}}}this.projectiles=this.projectiles.filter(p=>p.life>0);this.particles.update(dt);this.camera.update(this.player.x,this.player.y,dt,this.world.width,this.shake);this.updateBoss(dt);this.uiSys.refresh();if(this.player.hp<=0)this.die()}
 updateBoss(dt){if(!this.boss&&this.player.x>8100){this.boss=new Boss(8550,500);this.dialogue("THE HOLLOW KING","The forgotten throne still has a king.");this.uiSys.boss(true)}if(this.boss){this.boss.update(dt,this);if(this.boss.dead){this.state="victory";$("victory").classList.remove("hidden");$("hud").classList.add("hidden")}}}
 attack(){this.player.attackTimer=.18;this.shake=.08;for(const e of this.enemies){if(Math.abs(e.x-this.player.x)<105&&Math.abs(e.y-this.player.y)<75)e.hit(this.player.attackDamage,this)}if(this.boss&&Math.abs(this.boss.x-this.player.x)<125&&Math.abs(this.boss.y-this.player.y)<85)this.boss.hit(this.player.attackDamage,this);this.audio.sword()}
 magic(){if(this.player.mp<15)return;this.player.mp-=15;this.projectiles.push({x:this.player.x+this.player.face*35,y:this.player.y+25,vx:this.player.face*540,life:2,damage:this.player.magicDamage,boss:false});this.particles.burst(this.player.x,this.player.y+25,8,"#6fc9ff");this.audio.magic()}
 dialogue(name,text){this.dialog={name,text};this.uiSys.dialog(true)}
 advanceDialog(){if(!this.dialog)return;this.dialog=null;this.uiSys.dialog(false)}
 interact(){if(this.dialog){this.advanceDialog();return}for(const n of this.npcs)if(Math.abs(n.x-this.player.x)<75){this.dialogue(n.name,n.text);return}for(const c of this.chests)if(!c.open&&Math.abs(c.x-this.player.x)<65){c.open=true;this.player.coins+=20;this.player.maxHp+=8;this.player.hp=this.player.maxHp;this.dialogue("TREASURE","You found "+c.reward+". Your strength increases.");this.save();return}for(const cp of this.checkpoints)if(Math.abs(cp.x-this.player.x)<55){cp.active=true;this.player.spawn.x=cp.x;this.player.spawn.y=cp.y;this.player.hp=this.player.maxHp;this.player.mp=this.player.maxMp;this.dialogue("ANCIENT SHRINE","The shrine binds your spirit to this place.");this.save();return}}
 die(){if(this.state!=="playing")return;this.state="dead";$("death").classList.remove("hidden");$("hud").classList.add("hidden")}
 respawn(){this.player.x=this.player.spawn.x;this.player.y=this.player.spawn.y;this.player.hp=this.player.maxHp;this.player.mp=this.player.maxMp;this.state="playing"}
 toggleInventory(){if(this.state==="playing"){this.state="inventory";this.uiSys.inventory(true)}else if(this.state==="inventory"){this.state="playing";this.uiSys.inventory(false)}}
 togglePause(){if(this.state==="playing"){this.state="paused";$("pause").classList.remove("hidden")}else if(this.state==="paused"){this.state="playing";$("pause").classList.add("hidden")}}
 save(){this.saveSys.write(this.player,this.chests,this.checkpoints,this.areaIndex)}
 restore(){const s=this.saveSys.read();if(s){Object.assign(this.player,s.player);this.chests.forEach((c,i)=>c.open=!!s.chests?.[i]);this.checkpoints.forEach((c,i)=>c.active=!!s.checkpoints?.[i])}}
 toast(t){this.dialogue("SYSTEM",t)}
 draw(){const x=this.x;x.clearRect(0,0,this.W,this.H);this.world.draw(x,this.camera);for(const c of this.coins)if(!c.taken)this.world.drawCoin(x,c,this.camera);for(const c of this.chests)this.world.drawChest(x,c,this.camera);for(const n of this.npcs)this.world.drawNPC(x,n,this.camera);for(const cp of this.checkpoints)this.world.drawCheckpoint(x,cp,this.camera);for(const e of this.enemies)e.draw(x,this.camera);if(this.boss)this.boss.draw(x,this.camera);for(const p of this.projectiles)this.world.drawProjectile(x,p,this.camera);this.player.draw(x,this.camera);this.particles.draw(x,this.camera);if(this.dialog)this.uiSys.drawDialog(this.dialog)}}
