export class Player{
 constructor(x,y){this.x=x;this.y=y;this.w=34;this.h=58;this.vx=0;this.vy=0;this.face=1;this.hp=110;this.maxHp=110;this.mp=75;this.maxMp=75;this.attackDamage=12;this.magicDamage=20;this.defense=3;this.level=1;this.xp=0;this.coins=0;this.onGround=false;this.attackTimer=0;this.attackCD=0;this.magicCD=0;this.inv=0;this.spawn={x,y};this.weapon="Starter Sword";this.spell="Fire Orb"}
 update(dt,g){const k=g.keys,left=k.KeyA||k.ArrowLeft,right=k.KeyD||k.ArrowRight;this.vx+=(right-left)*850*dt;this.vx*=Math.pow(.0008,dt);this.vx=Math.max(-245,Math.min(245,this.vx));if(left)this.face=-1;if(right)this.face=1;if((k.Space||k.KeyW||k.ArrowUp)&&this.onGround){this.vy=-570;this.onGround=false;g.audio.jump()}this.vy+=1550*dt;const oldY=this.y,ny=this.y+this.vy*dt;let ground=600-this.h;for(const p of g.world.platforms)if(this.x+this.w>p.x&&this.x<p.x+p.w&&oldY+this.h<=p.y+10&&ny+this.h>=p.y&&this.vy>=0)ground=Math.min(ground,p.y-this.h);this.y=Math.min(ny,ground);this.onGround=this.y===ground&&this.vy>=0;if(this.onGround)this.vy=0;this.x+=this.vx*dt;this.x=Math.max(0,Math.min(g.world.width-this.w,this.x));this.attackCD-=dt;this.magicCD-=dt;this.attackTimer-=dt;this.inv-=dt;this.mp=Math.min(this.maxMp,this.mp+7*dt);
 if(k.KeyJ&&this.attackCD<=0){g.attack();this.attackCD=.38}if(k.KeyK&&this.magicCD<=0){g.magic();this.magicCD=.55}if(k.KeyE&&!this.eLock){this.eLock=true;g.interact()}if(!k.KeyE)this.eLock=false;
 for(const c of g.coins)if(!c.taken&&Math.hypot(this.x+17-c.x,this.y+28-c.y)<45){c.taken=true;this.coins++;g.audio.coin()}this.levelCheck(g)}
 levelCheck(g){const need=this.level*100;if(this.xp>=need){this.xp-=need;this.level++;this.maxHp+=12;this.maxMp+=8;this.attackDamage+=3;this.magicDamage+=3;this.hp=this.maxHp;this.mp=this.maxMp;g.dialogue("LEVEL UP","Level "+this.level+" reached. Your blade grows stronger.");g.audio.level()}}
 hitBy(d,g){if(this.inv>0)return;this.hp=Math.max(0,this.hp-Math.max(1,d-this.defense));this.inv=.7;g.shake=.15}
 gainXP(n,g){this.xp+=n;this.levelCheck(g)}
 draw(c,cam){const x=this.x-cam.x,y=this.y-cam.y;c.save();c.translate(x,y);if(this.face<0)c.scale(-1,1);const run=Math.sin(performance.now()/70*this.vx/100);c.fillStyle=this.inv>0?"#b7cde0":"#d0d2c9";c.fillRect(9,8,18,19);c.fillStyle="#1d2733";c.fillRect(6,26,25,27);c.fillStyle="#815b3d";c.fillRect(7,49,9,9);c.fillRect(21,49,9,9);c.fillStyle="#e0c77c";c.fillRect(11,13,4,4);c.fillRect(21,13,4,4);c.strokeStyle="#dbc36f";c.lineWidth=5;c.beginPath();c.moveTo(25,31);c.lineTo(this.attackTimer>0?62:53, this.attackTimer>0?5:15);c.stroke();c.restore()}}
